# Generated by Django 5.2 on 2025-05-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_singer_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
