# Generated by Django 5.2 on 2025-05-13 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='Course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
    ]
