# Generated by Django 5.2 on 2025-05-13 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_lesson_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptID', models.AutoField(primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
            ],
        ),
    ]
