# Generated by Django 5.2 on 2025-05-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_employee_name_employee_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dep_id',
            new_name='dept_ID',
        ),
    ]
