# Generated by Django 5.2 on 2025-05-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_dept_id_employee_deptid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='deptID',
            new_name='dep',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='deptID',
            new_name='dep',
        ),
    ]
